DROP TABLE IF EXISTS resources CASCADE;


CREATE TABLE resources (
  id SERIAL PRIMARY KEY NOT NULL,
  owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  url VARCHAR(255),
  description TEXT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  thumbnail_url VARCHAR(255) NOT NULL,
  category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE
);
